//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmniMIDIDebugWindow.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>One’s act, one’s profit.</string>\r\n  <string>Wake from death and return to" +
            " life.</string>\r\n  <string>The weak are meat; the strong eat.</string>\r\n  <strin" +
            "g>Evil cause, evil effect</string>\r\n  <string>Drunken life, dreamy death.</strin" +
            "g>\r\n  <string>Different body, same mind.</string>\r\n  <string>Spilt water will no" +
            "t return to the tray.</string>\r\n  <string>Fall down seven times, stand up eight." +
            "</string>\r\n  <string>A splendid child born from common parents.</string>\r\n  <str" +
            "ing>The fallen blossom returns not to the bough.</string>\r\n  <string>Perfect is " +
            "the enemy of good.</string>\r\n  <string>Who chases two rabbits catches neither.</" +
            "string>\r\n  <string>Everyone makes mistakes.</string>\r\n  <string>There\'s no accou" +
            "nting for taste.</string>\r\n  <string>Ignorance is bliss.</string>\r\n  <string>Per" +
            "severance is better than defeat.</string>\r\n  <string>Giving up at the first sign" +
            " of difficulty.</string>\r\n  <string>Fear is greater than the danger.</string>\r\n " +
            " <string>Only death will cure a fool.</string>\r\n  <string>Don\'t let yourself be " +
            "taken advantage of.</string>\r\n  <string>Arbitration in a quarrel is a godsend.</" +
            "string>\r\n  <string>Forgive and forget.</string>\r\n  <string>Farm when it\'s sunny," +
            " read when it rains.</string>\r\n  <string>Different strokes for different folks.<" +
            "/string>\r\n  <string>Disappear without a trace.</string>\r\n  <string>Good things, " +
            "many devils.</string>\r\n  <string>Time flies like an arrow.</string>\r\n  <string>T" +
            "he eyes are the mirror of the soul.</string>\r\n  <string>Cover the ears and steal" +
            " the bell.</string>\r\n  <string>To gamble as the dice fall.</string>\r\n  <string>T" +
            "he more stupid the child the dearer it is.</string>\r\n  <string>It is foolish to " +
            "deal with a fool.</string>\r\n  <string>Heart rather than appearance.</string>\r\n  " +
            "<string>If unreason comes, reason goes.</string>\r\n  <string>Poke a bush, a snake" +
            " comes out.</string>\r\n  <string>Even a fool has one talent.</string>\r\n  <string>" +
            "A coin to a cat.</string>\r\n  <string>Repentance never comes first.</string>\r\n  <" +
            "string>The environment makes our characters.</string>\r\n  <string>It\'s no use cry" +
            "ing over spilt milk.</string>\r\n  <string>There is luck in the last helping.</str" +
            "ing>\r\n  <string>A bad wife is a ruin of her husband.</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection LeMessages {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LeMessages"]));
            }
        }
    }
}
