//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmniMIDIDebugWindow.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Now 20% cooler!</string>\r\n  <string>AMOLED screens are not supported.</str" +
            "ing>\r\n  <string>Now with Google AdSense support!</string>\r\n  <string>I don\'t lik" +
            "e Windows 95.</string>\r\n  <string>A Hideo Kojima Game.</string>\r\n  <string>World" +
            " War III ready.</string>\r\n  <string>Powered by NVIDIA GameWorks.</string>\r\n  <st" +
            "ring>No gods or kings. Only man.</string>\r\n  <string>This is a line.</string>\r\n " +
            " <string>Now available for Android Oreo!</string>\r\n  <string>Featuring Dante fro" +
            "m the DmC series.</string>\r\n  <string>Now with overclocking capabilities!</strin" +
            "g>\r\n  <string>自業自得。</string>\r\n  <string>Haha same.</string>\r\n  <string>Easter eg" +
            "gs not included.</string>\r\n  <string>With full support for Windows 11!</string>\r" +
            "\n  <string>I hear something.</string>\r\n  <string>I love beautiful wood. Don\'t yo" +
            "u?</string>\r\n  <string>Approved by Donald Trump.</string>\r\n  <string>You are dea" +
            "d. Not big surprise!</string>\r\n  <string>This is a test. Congratulations!</strin" +
            "g>\r\n  <string>My Hero Academia is the best anime.</string>\r\n  <string>In-App pur" +
            "chases included!</string>\r\n  <string>Only for $49.99!</string>\r\n  <string>|     " +
            "| |     | |     |__</string>\r\n  <string>YAHOO YAYAYAYAYAYAHOOOOO!</string>\r\n  <s" +
            "tring>&amp;&amp; Knuckles!</string>\r\n  <string>Blinx is my waifu.</string>\r\n  <s" +
            "tring>Made with love by a furfag.</string>\r\n  <string>It sure is boring around h" +
            "ere...</string>\r\n  <string>With 400% more potatoes.</string>\r\n  <string>I am the" +
            " mustard of your doom!</string>\r\n  <string>Running on Java 1.7.0.</string>\r\n  <s" +
            "tring>This is not a drill!</string>\r\n  <string>Put that down, it\'s a prototype.<" +
            "/string>\r\n  <string>Wahoo!</string>\r\n  <string>Perhaps.</string>\r\n  <string>The " +
            "best soft-synth in the world.</string>\r\n  <string>Apple Dash and Pinkie Sparkle." +
            "</string>\r\n  <string>The real deal! Sort of.</string>\r\n  <string>Hey Scotty! Jes" +
            "us man.</string>\r\n  <string>I can\'t believe you\'ve done this.</string>\r\n  <strin" +
            "g>You know I had to do it to them.</string>\r\n  <string>* not supported by Apple." +
            "</string>\r\n  <string>Ching chong!</string>\r\n  <string>Better than VirtualMIDISyn" +
            "th.</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection LeMessages {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LeMessages"]));
            }
        }
    }
}
