//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmniMIDIDebugWindow.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring>Only death will cure a fool.</string>\r\n  <string>One’s act, one’s profit.<" +
            "/string>\r\n  <string>Don\'t wait. The time will never be just right.</string>\r\n  <" +
            "string>Life changes very quickly, in a very positive way, if you let it.</string" +
            ">\r\n  <string>Be the labour great or small, do it well or not at all.</string>\r\n " +
            " <string>If unreason comes, reason goes.</string>\r\n  <string>Repentance never co" +
            "mes first.</string>\r\n  <string>The sky speaks in a thousand colours.</string>\r\n " +
            " <string>A coin to a cat.</string>\r\n  <string>Wake from death and return to life" +
            ".</string>\r\n  <string>Forever is composed of nows.</string>\r\n  <string>Arbitrati" +
            "on in a quarrel is a godsend.</string>\r\n  <string>There is luck in the last help" +
            "ing.</string>\r\n  <string>There\'s no accounting for taste.</string>\r\n  <string>Ea" +
            "ch person must live their life as a model for others.</string>\r\n  <string>Once a" +
            " task is just begun, never leave it till it\'s done.</string>\r\n  <string>Giving u" +
            "p at the first sign of difficulty.</string>\r\n  <string>Change the world by being" +
            " yourself.</string>\r\n  <string>Aspire to inspire before we expire.</string>\r\n  <" +
            "string>Evil cause, evil effect</string>\r\n  <string>Fall down seven times, stand " +
            "up eight.</string>\r\n  <string>You may think I’m small, but I have a universe ins" +
            "ide my mind.</string>\r\n  <string>The fallen blossom returns not to the bough.</s" +
            "tring>\r\n  <string>The eyes are the mirror of the soul.</string>\r\n  <string>Keep " +
            "your face always toward the sunshine, and shadows will fall behind you.</string>" +
            "\r\n  <string>A year spent in artificial intelligence is enough to make one believ" +
            "e in God.</string>\r\n  <string>The programmer must seek both perfection of part a" +
            "nd adequacy of collection.</string>\r\n  <string>Most people would rather be certa" +
            "in they’re miserable, than risk being happy.</string>\r\n  <string>Nothing is impo" +
            "ssible. The word itself says \"I\'m possible!\".</string>\r\n  <string>The weak are m" +
            "eat; the strong eat.</string>\r\n  <string>Let us make our future now, and let us " +
            "make our dreams tomorrow\'s reality.</string>\r\n  <string>Heart rather than appear" +
            "ance.</string>\r\n  <string>You are enough just as you are.</string>\r\n  <string>No" +
            " matter what you\'re going through, there\'s a light at the end of the tunnel.</st" +
            "ring>\r\n  <string>Believe you can and you\'re halfway there.</string>\r\n  <string>T" +
            "he more stupid the child the dearer it is.</string>\r\n  <string>Die with memories" +
            ", not dreams.</string>\r\n  <string>Poke a bush, a snake comes out.</string>\r\n  <s" +
            "tring>Keep your face to the sunshine and you cannot see a shadow.</string>\r\n  <s" +
            "tring>Everyone makes mistakes.</string>\r\n  <string>It is foolish to deal with a " +
            "fool.</string>\r\n  <string>Different body, same mind.</string>\r\n  <string>Some pe" +
            "ople look for a beautiful place. Others make a place beautiful.</string>\r\n  <str" +
            "ing>Be the change that you wish to see in the world.</string>\r\n  <string>Farm wh" +
            "en it\'s sunny, read when it rains.</string>\r\n  <string>Every moment is a fresh b" +
            "eginning.</string>\r\n  <string>Time flies like an arrow.</string>\r\n  <string>Love" +
            " takes off masks that we fear we cannot live without and know we cannot live wit" +
            "hin.</string>\r\n  <string>Ignorance is bliss.</string>\r\n  <string>The bad news is" +
            " time flies. The good news is you\'re the pilot.</string>\r\n  <string>Act as if wh" +
            "at you do makes a difference. It does.</string>\r\n  <string>A bad wife is a ruin " +
            "of her husband.</string>\r\n  <string>Forgive and forget.</string>\r\n  <string>A we" +
            "irdo but I\'m real though.</string>\r\n  <string>Never regret anything that made yo" +
            "u smile.</string>\r\n  <string>The giving of love is an education in itself.</stri" +
            "ng>\r\n  <string>No matter what people tell you, words and ideas can change the wo" +
            "rld.</string>\r\n  <string>You get what you give.</string>\r\n  <string>The environm" +
            "ent makes our characters.</string>\r\n  <string>Perseverance is better than defeat" +
            ".</string>\r\n  <string>If I cannot do great things, I can do small things in a gr" +
            "eat way.</string>\r\n  <string>Happiness is when what you think, what you say, and" +
            " what you do are in harmony.</string>\r\n  <string>Perfect is the enemy of good.</" +
            "string>\r\n  <string>It is never too late to be what you might have been.</string>" +
            "\r\n  <string>Don\'t let yourself be taken advantage of.</string>\r\n  <string>Stay c" +
            "lose to anything that makes you glad you are alive.</string>\r\n  <string>Limit yo" +
            "ur \"always\" and your \"nevers\".</string>\r\n  <string>Happy people plan actions, th" +
            "ey don’t plan results.</string>\r\n  <string>Fear is greater than the danger.</str" +
            "ing>\r\n  <string>Success is not final, failure is not fatal: it is the courage to" +
            " continue that counts.</string>\r\n  <string>Cover the ears and steal the bell.</s" +
            "tring>\r\n  <string>Good things, many devils.</string>\r\n  <string>Disappear withou" +
            "t a trace.</string>\r\n  <string>Never perfect - always genuine. Be yourself.</str" +
            "ing>\r\n  <string>Different strokes for different folks.</string>\r\n  <string>It\'s " +
            "no use crying over spilt milk.</string>\r\n  <string>Own who you are.</string>\r\n  " +
            "<string>Who chases two rabbits catches neither.</string>\r\n  <string>Try to be a " +
            "rainbow in someone else\'s cloud.</string>\r\n  <string>A splendid child born from " +
            "common parents.</string>\r\n  <string>Even a fool has one talent.</string>\r\n  <str" +
            "ing>My mission in life is not merely to survive, but to thrive.</string>\r\n  <str" +
            "ing>Spilt water will not return to the tray.</string>\r\n  <string>Love for all, h" +
            "atred for none.</string>\r\n  <string>Happiness often sneaks in through a door you" +
            " didn\'t know you left open.</string>\r\n  <string>Never bend your head. Always hol" +
            "d it high. Look the world straight in the eye.</string>\r\n  <string>Drunken life," +
            " dreamy death.</string>\r\n  <string>To gamble as the dice fall.</string>\r\n  <stri" +
            "ng>When you have a dream, you\'ve got to grab it and never let go.</string>\r\n</Ar" +
            "rayOfString>")]
        public global::System.Collections.Specialized.StringCollection LeMessages {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LeMessages"]));
            }
        }
    }
}
