'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.34209
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    'tramite uno strumento quale ResGen o Visual Studio.
    'Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    'con l'opzione /str oppure ricompilare il progetto VS.
    '''<summary>
    '''  Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("keppydrvcfg.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        '''  ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Icon simile a (Icona).
        '''</summary>
        Friend ReadOnly Property _128() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_128", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Messing up with the default list can potentially hang/block your PC,
        '''since the driver is loaded by some system processes. (Especially on Windows XP)
        '''
        '''Use this function carefully..
        '''</summary>
        Friend ReadOnly Property AdvancedBlackListWarning() As String
            Get
                Return ResourceManager.GetString("AdvancedBlackListWarning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Driver: Chris Moeller, Brad Miller and Riccardo Loi
        '''BASS libraries: Ian Luck
        '''Setup: NSIS Project
        '''Blacklist system: Chris Moeller and Riccardo Loi
        '''Soundfont preloading system: Chris Moeller
        '''On-The-Fly settings changes: Riccardo Loi and Chris Moeller
        '''XAudio/DirectSound switcher: Riccardo Loi
        '''Configurator: Original C++ version by Chris Moeller, ported to .NET by Riccardo Loi
        '''
        '''Chris Moeller: Kode54, also the original co-creator of the driver
        '''Brad Miller: mudlord, also the original co-creator of the dr [stringa troncata]&quot;;.
        '''</summary>
        Friend ReadOnly Property Credits() As String
            Get
                Return ResourceManager.GetString("Credits", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Copyright (c) 2011-2015 Brad Miller, Chris Moeller and Riccardo Loi
        '''All rights reserved.
        '''     
        '''Redistribution and use of this code or any derivative works are permitted provided that the following conditions are met:
        '''
        '''1) Redistributions may not be sold, nor may they be used in a commercial product or activity, without direct written/verbal consent of the authors. 
        '''
        '''2) Redistributions that are modified from the original source *must* include the complete source code, *including* the source code for al [stringa troncata]&quot;;.
        '''</summary>
        Friend ReadOnly Property Credits2() As String
            Get
                Return ResourceManager.GetString("Credits2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property exclamation_red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exclamation_red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Icon simile a (Icona).
        '''</summary>
        Friend ReadOnly Property gear() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("gear", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a &lt;!doctype html&gt;
        '''&lt;html&gt;
        '''&lt;head&gt;
        '''    &lt;title&gt;Driver changelog&lt;/title&gt;
        '''&lt;/head&gt;
        '''&lt;body&gt;
        '''Release 1.5.0.25
        '''&lt;ul style=&quot;list-style-type:disc&quot;&gt;
        '''  &lt;li&gt;Added debug mode to the configurator! (You can use it manually, by launching the configurator within a CMD window, and adding the -debug parameter, or by using the link in the Start menu)&lt;/li&gt;
        '''  &lt;li&gt;Added a secret mode in the configurator! :)&lt;/li&gt;
        '''  &lt;li&gt;Minor fixes to the driver.&lt;/li&gt;
        '''&lt;/ul&gt;  
        '''&lt;hr&gt;
        '''Release 1.5 Bugfix 220
        '''&lt;ul style=&quot;list-style-type:disc&quot;&gt;
        '''  &lt; [stringa troncata]&quot;;.
        '''</summary>
        Friend ReadOnly Property keplog() As String
            Get
                Return ResourceManager.GetString("keplog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property keppydriverlogobyfrozennotrasparency2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("keppydriverlogobyfrozennotrasparency2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property kepsdigital() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("kepsdigital", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a While focused on a MIDI app that is using the driver, you will be able to do the following:
        '''
        '''HOME: Reload the soundfont list in memory, useful when you change the soundfonts on-the-fly.
        '''INSERT: Reset the MIDI synth, by dropping all the current notes.
        '''
        '''(The speed of the soundfont preloading is mainly influenced by your hard disk/solid state drive.).
        '''</summary>
        Friend ReadOnly Property Shortcuts() As String
            Get
                Return ResourceManager.GetString("Shortcuts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Warning_Box_Yellow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Warning_Box_Yellow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
