/*
Keppy's Synthesizer errors list
*/

static TCHAR * errname[49] =
{
	L"BASS_OK",
	L"BASS_ERROR_MEM",
	L"BASS_ERROR_FILEOPEN",
	L"BASS_ERROR_DRIVER",
	L"BASS_ERROR_BUFLOST",
	L"BASS_ERROR_HANDLE",
	L"BASS_ERROR_FORMAT",
	L"BASS_ERROR_POSITION",
	L"BASS_ERROR_INIT",
	L"BASS_ERROR_START",
	L"BASS_ERROR_SSL",
	L"",
	L"",
	L"",
	L"",
	L"BASS_ERROR_ALREADY",
	L"",
	L"",
	L"",
	L"",
	L"BASS_ERROR_NOCHAN",
	L"BASS_ERROR_ILLTYPE",
	L"BASS_ERROR_ILLPARAM",
	L"BASS_ERROR_NO3D",
	L"BASS_ERROR_NOEAX",
	L"BASS_ERROR_DEVICE",
	L"BASS_ERROR_NOPLAY",
	L"BASS_ERROR_FREQ",
	L"",
	L"BASS_ERROR_NOTFILE",
	L"",
	L"BASS_ERROR_NOHW",
	L"",
	L"BASS_ERROR_EMPTY",
	L"BASS_ERROR_NONET",
	L"BASS_ERROR_CREATE",
	L"BASS_ERROR_NOFX",
	L"BASS_ERROR_PLAYING",
	L"",
	L"BASS_ERROR_NOTAVAIL",
	L"BASS_ERROR_DECODE",
	L"BASS_ERROR_DX",
	L"BASS_ERROR_TIMEOUT",
	L"BASS_ERROR_FILEFORM",
	L"BASS_ERROR_SPEAKER",
	L"BASS_ERROR_VERSION",
	L"BASS_ERROR_CODEC",
	L"BASS_ERROR_ENDED",
	L"BASS_ERROR_BUSY",
};

static TCHAR * errdesc[49] =
{
	L"Nothing's wrong.",
	L"There is insufficient memory.",
	L"The file could not be opened.",
	L"There is no available device driver. The device may already be in use.",
	L"The sample buffer was lost.",
	L"An invalid handle has been used.",
	L"The sample format is not supported by the device/drivers.",
	L"The requested position is invalid, eg. it is beyond the end or the download has not yet reached it",
	L"BASS_Init has not been successfully called.",
	L"BASS_Start has not been successfully called",
	L"SSL/HTTPS support isn't available",
	L"",
	L"",
	L"",
	L"",
	L"Stream already initialized/paused/whatever",
	L"",
	L"",
	L"",
	L"",
	L"Can't get a free channel",
	L"An illegal type was specified",
	L"An illegal parameter was specified",
	L"No 3D support",
	L"No EAX support",
	L"Illegal device number",
	L"Not playing",
	L"Illegal sample rate",
	L"",
	L"The stream is not a file stream",
	L"",
	L"No hardware voices available",
	L"",
	L"The MOD music has no sequence data",
	L"No internet connection could be opened",
	L"Couldn't create the file",
	L"Effects are not available",
	L"The channel is playing"
	L"",
	L"Requested data is not available",
	L"The channel is a 'decoding channel'",
	L"A sufficient DirectX version is not installed",
	L"Connection timed out",
	L"Unsupported file format",
	L"Unavailable speaker",
	L"Invalid BASS version (used by add-ons)"
	L"Codec is not available/supported",
	L"The channel/file has ended",
	L"The device is busy (eg. in 'exclusive' use by another process)", L"a",
};