//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeppySynthDebugWindow.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Better than VirtualMIDISynth.</string>
  <string>The best soft-synth in the world.</string>
  <string>I don't like Windows 95.</string>
  <string>I love beautiful wood. Don't you?</string>
  <string>Approved by Donald Trump.</string>
  <string>Hey Scotty! Jesus man.</string>
  <string>Now available for Android Oreo!</string>
  <string>With 400% more potatoes.</string>
  <string>* not supported by Apple.</string>
  <string>Powered by NVIDIA GameWorks.</string>
  <string>With full support for Windows 11!</string>
  <string>Only for $49.99!</string>
  <string>World War III ready.</string>
  <string>MAH BOI.</string>
  <string>Easter eggs not included.</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection LeMessages {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LeMessages"]));
            }
        }
    }
}
